### ISSUE TITLE
Create job that installs qcs and runs its own tests

### ISSUE THREAD

**Issue by kdelee** [quipucords/ci#13]
This job should:
*  clone https://github.com/quipucords/quipucords
* install necessary system packages
* install other requirements from requirements files using pip
* run qcs unit tests

This job can be extended to run camayoc tests later once we have api client and tests in place.

**Comment by kdelee** [comment]
I am going to use [pytest-django](http://pytest-django.readthedocs.io/en/latest/tutorial.html) so I can run the unit test with pytest and generate a test report

**Comment by elyezer** [comment]
As mentioned on the related PR this issue should run Camayoc tests for qcs instead of its unittests. The qcs unittests are being run on Travis already and there is no need to duplicate them on Jenkins.

**Comment by kdelee** [comment]
@elyezer 

FYI I think this is ready whenever you are, but no rush.

The job now checks out camayoc and quipucords and runs the development server in the background while the tests run against it. It then produces a report based on the camayoc test results and kills the server.

It runs nightly and checks every half hour for code changes in the git repos, and runs if there is new code.
