### ISSUE TITLE
Create a jenkins pipeline to run Yupana Tests

### ISSUE THREAD

**Issue by himmAllRight** [quipucords/ci#141]
# Issue type
- Enhancement

# Description of issue
Now that basic testing for yupana has been added to [camayoc](https://github.com/quipucords/camayoc), a Jenkins pipeline should to created to automatically run them.

# Completion checklist
To close this issue, the following items must be satisfied:
- [x] Pipeline defined that runs the yupana tests
- [x] Jenkins pipeline job created to automatically run yupana tests

# Related development issues
[Camayoc Epic: Setup and configure yupana automated testing environment #315](https://github.com/quipucords/camayoc/issues/315)

**Comment by ruda** [comment]
I'm looking at https://sonar-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/yupana-test-pipeline/activity/ I assume that it is done. Feel free to undo this if there is any issue (like a test that must be present) that I missed.
