### ISSUE TITLE
Work around upstream ansible bug

### ISSUE THREAD

**Issue by kdelee** [quipucords/ci#15]
[Anisble bug](https://github.com/ansible/ansible/issues/30663)

Camayoc runs on python 3.6, but ansible 2.4.0 has a bug that makes it unable to load inventory files in yaml while running python 3.6. 

The work around that should allow our nightly remote scan jobs to proceed is to make the jobs install ansible 2.3.2 in the virtual environment instead of 2.4, because rho pulls in the latest ansible version by default when installing. 

This work around can be removed when the bug is fixed. The proposed fixed has been merged and the issue closed, but the fix is not in a release yet.
The ansible maintainers say [this fix will come out with 2.4.1](https://github.com/ansible/ansible/issues/30663#issuecomment-333274012)

**Comment by kdelee** [comment]
@elyezer should the PR with the bug fix close this issue, or should the issue stay open until the work around can be removed?

**Comment by elyezer** [comment]
Let's close this issue. The workaround includes a reference from where it came from and this issue provide good detail why we needed it.
