### ISSUE TITLE
Create an ansible role and playbook for setting up new systems with the appropriate scan users

### ISSUE THREAD

**Issue by chambridge** [quipucords/ci#2]
Role should create two users:
- scanadmin
- scanbasic

Role should add a line to  `/etc/sudoers` to give `scanadmin` admin privileges

Role should add Jenkins ssh key file as authorized key for users:
- root
- scanadmin
- scanbasic

**Comment by elyezer** [comment]
> Role should add a line to /etc/sudoers to give scanadmin admin privileges

Will that enable password less sudo, right?

**Comment by chambridge** [comment]
@elyezer: yes
