### ISSUE TITLE
Create a machine on vCenter with JBoss EAP 5.x installed on a RHEL 5

### ISSUE THREAD

**Issue by elyezer** [quipucords/ci#31]
Currently on the test matrix there are machines with JBoss EAP 6 and 7 installed but EAP 5 is also wanted. Make sure we have a machine with JBoss EAP 5 installed on a RHEL5.

**Comment by kdelee** [comment]
This fell off my radar, I will pick up for the beginning of Sprint 15

**Comment by kdelee** [comment]
@noahl FYI picking this up for early next week

**Comment by kdelee** [comment]
Done, I have updated our jbosseap-rhel5 machine to have jboss eap 5.2.0
