### ISSUE TITLE
Update quipucords nightly job to use docker container

### ISSUE THREAD

**Issue by kdelee** [quipucords/ci#38]
The recommended path to run quipucords is to build and run the docker image. 

We should look into if we can do this on the nodepool nodes so we can [follow the docs for building and running the image](https://github.com/quipucords/quipucords#container-image)

@elyezer Do you anticipate any problems getting docker running on those nodepool nodes?

**Comment by elyezer** [comment]
Docker should run just fine on the nodes. Also docker should be already installed [1], so you just need to `systemctl start` it and use.

[1] https://github.com/quipucords/ci/blob/master/ansible/roles/nodepool/files/elements/jenkins-slave/package-installs.yaml#L2

**Comment by elyezer** [comment]
Be aware that now docker defaults to using port 443 (https)
