### ISSUE TITLE
Upgrade Jenkins to 2.x

### ISSUE THREAD

**Issue by kdelee** [quipucords/ci#46]
We need to schedule a time to update our Jenkins to 2.x.

Please respond here if you have any constraints about when this can happen.

**Comment by elyezer** [comment]
I've opened a ticket to schedule the upgrade. I will update here when I get more information.

**Comment by elyezer** [comment]
Jenkins was upgraded yesterday and it is working. I waited until today to make sure it was really working after the nightly jobs being run.
