### ISSUE TITLE
Automate beta testing

### ISSUE THREAD

**Issue by elyezer** [quipucords/ci#50]
Create a pipeline job that will perform the beta testing:

1. Install quipucords server
2. Install qpc client
3. Perform a scan and check the report

The pipeline should include both RHEL 6 and RHEL 7 and both should work in order to have a green build. Also both should be run no matter if the first one tried failed or not.

**Comment by kdelee** [comment]
I have this currently running as a regular job on fedora 27, need to update it to meet these specifications

**Comment by kdelee** [comment]
After discussion with @elyezer I think I will do this but use the template approach because I think it will require less research time

**Comment by kdelee** [comment]
When working on this PR, also should get container image from the github releases page:
http://quipucords.readthedocs.io/en/beta/beta.html#installing-the-quipucords-server-container-image
