### ISSUE TITLE
Update qcs references to qpc

### ISSUE THREAD

**Issue by chambridge** [quipucords/ci#70]
# Issue type
- Other

# Description of issue
We inconsistently reference **quipucords** between this project and the main project. I'd prefer we reference both using `qpc` as the shorthand.

# Completion checklist
To close this issue, the following items must be satisfied:
- [ ] Update all files, project names, and other references to use `qpc` instead of `qcs`
- [ ] Push all job updates to Jenkins

**Comment by chambridge** [comment]
@quipucords/quality-engineers 
Thoughts?

**Comment by kdelee** [comment]
:tada: :taco: :+1: :100: :crystal_ball: are my thoughts on consistency.

Only thing is we do need some way to distinguish between the server and the command line client. Maybe `qpc-server` and `qpc-cli` when necessary? At all other times, `qpc`?

**Comment by kdelee** [comment]
Would be good to update references in Camayoc too
