### ISSUE TITLE
Look into creating rhel 7.5 images for Jenkins

### ISSUE THREAD

**Issue by kdelee** [quipucords/ci#75]
RHEL 7.5 just got released. 

Look into creating images with diskimage-builder. If successful, update the documentation and any other needed files.

**Comment by kdelee** [comment]
@elyezer I've got an image that I can log into with the jenkins credentials...set up jenkins to use the template image...it showed up on main jenkins config like I expected. Then I created a job to use it. 

Sparking of a build of the job makes an instance be created on OS and I can log into it with the jenkins credentials, but Jenkins keeps saying that the node is still offline. Not sure whats going on with that.

**Comment by kdelee** [comment]
Well I looked at the logs and it seems that jenkins wants there to be java on the machine.

I tried to do it while the image was alive but it did not seem to help. I'll try and roll a fresh base image.

**Comment by kdelee** [comment]
That fixed it, needed to have java-1.8.0-openjdk-devel

**Comment by elyezer** [comment]
Yes, Jenkins uses a Java client on the slaves so it can communicate with the slave

**Comment by kdelee** [comment]
@elyezer I have now updated the labels on Jenkins and the rhel7 label now points to the rhel 7.5 image on openstack

**Comment by elyezer** [comment]
Thank you
